### ISSUE TITLE
espower 2.0 milestone

### ISSUE THREAD

**Issue by twada** [power-assert-js/espower#29]
Milestone for espower 2.0.0 release
#### New Features

espower 2.0.0 embeds value capturing helper into transpiled code (#26). Therefore,
- enhanced assertion doesn't have to have magical [`_capt` and `_expr` methods](https://github.com/twada/empower-core/issues/1)
- makes capturing logic in [empower-core](https://github.com/twada/empower-core) unnecessary
- solves [possible async problem](https://github.com/power-assert-js/empower/issues/21)

espower 2.0.0 exposes visitor object for estraverse (#31). Therefore,
- works with [merge-estraverse-visitors](https://github.com/twada/merge-estraverse-visitors) to integrate with [empower-assert](https://github.com/teppeis/empower-assert)
#### Breaking Changes

The `destructive` option has been removed (#30).
- New behavior is like `destructive: true`, means that passed AST is modified directly.
- If you do not want your AST to be modified, you should deep clone your AST by yourself.
#### TODO
- [x] embed value capturing helper into transpiled code (#26)
- [x] remove destructive option (#30)
- [x] expose visitor object for estraverse (#31)
- [x] release [merge-estraverse-visitors](https://github.com/twada/merge-estraverse-visitors) module
- [x] hide `Instrumentor` class ([afa380f](https://github.com/power-assert-js/espower/commit/afa380f949acf4366d9226c44d89cb7ccdfd72c5))
- [x] hide `AssertionVisitor` class ([afa380f](https://github.com/power-assert-js/espower/commit/afa380f949acf4366d9226c44d89cb7ccdfd72c5))
- [x] drop IE8 support
- [x] drop Node v0.10 support
- [x] stop providing prebuilt bundle for browsers
- [x] drop bower support

**Comment by twada** [comment]
Done 🎉  [Release v2.0.0: Embed value capturing helper (2016-11-11) · power-assert-js/espower](https://github.com/power-assert-js/espower/releases/tag/v2.0.0)
